rockyhawk64/CommandPanels

pom.xml
src/me/rockyhawk/commandpanels/classresources/Serializer.java
src/me/rockyhawk/commandpanels/classresources/SerializerUtils.java
src/me/rockyhawk/commandpanels/commandtags/tags/standard/BasicTags.java

- CommandTags: minimessage=
Tested with: 1.19, 1.18, 1.16
**_DISCLAIMER:_** Only works on Paper 1.18 or newer! Other Plattforms or earlier versions can't use this CommandTag

Added MiniMessage Support as CommandTag

---

resource/config.yml
src/me/rockyhawk/commandpanels/CommandPanels.java
src/me/rockyhawk/commandpanels/commands/Commandpanelsreload.java
src/me/rockyhawk/commandpanels/commandtags/CommandTags.java

These Commits have the following changes:
- Add Toggles to all Purchase-Messages so that Players can disable those which they don't want.
- Remove the Space after the `format.tag`-Variable, so that Players don't have a space before their message if they remove the Text from the Tag
- Switched in some files from a "file-own" declaration of the `tag`-configvalue to the `plugin.tag`-variable defined by the `CommandPanels.java`-File

Paywall-Message-Toggles | Remove Space after Tag | Use Tag provided by Main Class

---

src/me/rockyhawk/commandpanels/commandtags/tags/standard/BungeeTags.java

- Added `force-server=` Command Tag
- Changed the behavior of `server=` Command Tag 
**Changes to `server=` Command tag:**
It will now require the player to have the correct permission _(bungeecord.command.server.[server])_ to enter a restricted server.
**Behaviour of `force-server=` Command Tag:**
It behaves as `server=` does in previous versions of CP and sends the player to the desired server without any permission-checks
This PR was tested on **MC 1.19.2** with `Waterfall 1.19#504` and `Paper 1.19.2#135`.

Add force-server= CommandTag

---

src/me/rockyhawk/commandpanels/commandtags/CommandTags.java
src/me/rockyhawk/commandpanels/commandtags/tags/economy/BuyCommandTags.java
src/me/rockyhawk/commandpanels/commandtags/tags/economy/BuyItemTags.java
src/me/rockyhawk/commandpanels/commandtags/tags/economy/SellItemTags.java

Adds PAPI Placeholder parsing to most if not all "Purchase"-related success/failure messages of CP Adds %cp-args% parsing to most if not all "Purchase"-related success/failure messages of CP
Tested on 1.19.2 with Paper Build 270 _(Yes, a little bit outdated)_ but should work on every Version which is supported by CP.

Add PAPI and %cp-args%

---

resource/config.yml
src/me/rockyhawk/commandpanels/CommandPanels.java
src/me/rockyhawk/commandpanels/commandtags/tags/standard/BasicTags.java

1. Added Config Option to enable the Command Tag `minimessage=` for other Paper-forks on 1.18 or above.
2. Also added a Warning on Startup if that option is enabled. Can be disabled if the server owner intends to use a Paper-fork.
Config Options added:
- `allow-unsafe-mini-message` | Default: `false`
- `disable-unsafe-mm-warning` | Default: `false`
Tested on Spigot 1.19.3 and Paper 1.19.3.
Disclaimer: Command Panels only supports Paper and Spigot! Usage of other Forks is at own risk and no support is guaranteed.

Added Config-Option to enable MiniMessage-CommandTag on Non-Paper forks + Warning

---

resource_example/example_middle_two.yml

This will fix the `example middle two` to be compatible with recent placeholder math versions.
In a recent placeholder math version (not sure which) `%math_1+14*{cp-data-onlinepage}%` will no longer return a whole number, so this breaks `cp-player-online`. So now `%math_0:_1+14*{cp-data-onlinepage}` needs to be used, the new `_0: part means return no decimals. So now the  `cp-player-online` will work again because it is getting a whole number. This new addition is repeated for every player head in the menu. This bug can be found by enabling debug mode, then open the gui, then in the console it says ...
```
[19:27:46 INFO]: [CommandPanels] The plugin has generated a debug error, find the error below
[19:27:46 WARN]: java.lang.NumberFormatException: For input string: "1.000"
[19:27:46 …
```

Made `example middle two` compatible with newish placeholder math.

---

pom.xml
src/me/rockyhawk/commandpanels/classresources/ItemCreation.java
src/me/rockyhawk/commandpanels/classresources/placeholders/Placeholders.java

- Update Code to newer VotingPlugin API
- Update Spigot API to 1.20-R0.1-SNAPSHOT
- Add ArmorTrim Option for Item Settings
Adding `trim: <Material> <Pattern>` to the item-settings will add the newly added Trims to any armor which can be customized by those.
List of those can be found here: [Trim Pattern](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/trim/TrimPattern.html) and [Trim Material](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/trim/TrimMaterial.html)
The new Option was tested on a Minecraft _**1.20.1**_ Server running _**Paper Build 58**_.

Added ArmorTrim Option and other changes

---

src/me/rockyhawk/commandpanels/classresources/GetCustomHeads.java

This PR fixes the NullPointerException with Custom Heads in Minecraft 1.20.2.
Tested with Paper **(1.20.1 Build 196 & 1.20.2 Build 207)** and Spigot **(1.20.2 Build 3904-Spigot-224dad5-1bf30a4)**.

Fix Error with Custom Heads on 1.20.2

---

resource/config.yml
src/me/rockyhawk/commandpanels/commands/CommandPanelImport.java

Implements the config toggle `enable-import-command` which is set to `false` in the default configuration.
This is meant to increase security for server owners which don't make use of that feature.
Everyone who wants to use this feature can just enable it by setting the toggle to `true`.
Server used for testing: `Minecraft 1.20.4 with paper-1.20.4-381` but should work on any version with this feature.

Implement toggle for disabling the Import Command.

---

src/me/rockyhawk/commandpanels/classresources/ItemCreation.java

Commented out the nbt part of cpg due to how its causing errors on panels just created since material and such is not removed from the nbt. Needs a way to ONLY show custom nbt data.

Disabled /cpg nbt auto grabber as its causing issues.

---

src/me/rockyhawk/commandpanels/classresources/HasSections.java

Fixed hasperm crashing panels on null player. Now it will automatically return as false if no player is found in the check. This allows panels with player input to be open without the placeholder thats being checked by the hasperm.
Will be last quick fix before i start work on nbt system.

Hasperm null fix

---

src/me/rockyhawk/commandpanels/classresources/placeholders/Placeholders.java
src/me/rockyhawk/commandpanels/openwithitem/UtilsOpenWithItem.java

Quick hotfix for %cp-material-slot% not returning correctly on legacy clients.

Fix for %cp-material-slot% and legacy ids.

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/need-help.yml
src/me/rockyhawk/commandpanels/classresources/ItemCreation.java
src/me/rockyhawk/commandpanels/commandtags/CommandTags.java

Fix for Half on mmo= paywall=, multipaywall w/custom items, added IGNORENBT to item-paywall= for edge cases like spawner types ONLY WORKS ON NORMAL MATERIAL CHECKS
Half items should not happen with mmo= custom items in item paywalls anymore. This was caused by the main section checking before the mmo= section checked. Now it only checks mmo= if its an mmo= and does not continue to the main custom item check after.
Multipaywall was fixed due to custom model data not being taken into account on IsIdentical check.
IGNORENBT was added as a simple .contains check in item-paywall so that if you want to require spawners of any type in a spawner check it can work. ONLY WORKS ON NORMAL MATERIAL CHECKS NOT CUSTOM ITEM SECTIONS!
Also reduced version options for github down to last ingame editor …

Fixes to mmo= paywalls, multipaywalls, minor changes to item-paywall=

---

src/me/rockyhawk/commandpanels/classresources/ItemCreation.java
src/me/rockyhawk/commandpanels/commandtags/CommandTags.java
src/me/rockyhawk/commandpanels/nbt/NBTManager.java

Changes to the logic for item-paywall= Uses IsIdentical check instead of the other checks we were doing and uses the GenerateItemFromConfig to make the sell item even with mmo= and custom items.
Changes to the noAttributes tag and how it works. Instead of turning off the hiding noAttributes now hides them instead.
Addition quick change to the nbtmanager to get the correct type instead of always string. Unsure on if this affects anything since i have not tested it.

Changes to item-paywall=

---

pom.xml
src/me/rockyhawk/commandpanels/CommandPanels.java
src/me/rockyhawk/commandpanels/classresources/SerializerUtils.java
src/me/rockyhawk/commandpanels/classresources/placeholders/Placeholders.java
src/me/rockyhawk/commandpanels/commandtags/paywalls/Hasperm.java
src/me/rockyhawk/commandpanels/commandtags/tags/standard/BasicTags.java
src/me/rockyhawk/commandpanels/openpanelsmanager/OpenGUI.java

Added `%cp-name-<slot>%` which will return the name of the item in that slot. If no name it will use item type like COBBLESTONE
Added `%cp-lore-<slot>%` which returns the lore for the slot with \n added to the ends of each line as a spacer/splitter. EXAMPLE:
```
lore:
- hello world
- this is me
```
would return `"hello world\nthis is me"` and
```
lore:
- hello world
```
Would return `"hello world\n"`
both return `""` if empty/does not exist.

Additional placeholders - name-slot, lore-slot AND hasnoperm=

---

src/me/rockyhawk/commandpanels/Utils.java
src/me/rockyhawk/commandpanels/classresources/ExecuteOpenVoids.java
src/me/rockyhawk/commandpanels/classresources/MiniMessageUtils.java
src/me/rockyhawk/commandpanels/commandtags/tags/other/SpecialTags.java
src/me/rockyhawk/commandpanels/commandtags/tags/standard/BungeeTags.java
src/me/rockyhawk/commandpanels/interactives/input/PlayerInput.java
src/me/rockyhawk/commandpanels/interactives/input/UserInputUtils.java

Some versions of purpur used an older version of minimessage which used a slighly different method to call it. Added a check to see which method it uses and falls back to nothing if not found as it would crash the plugin on start if it was not found.

Minimessage old vs new fix.

---

src/me/rockyhawk/commandpanels/classresources/ItemCreation.java

Enchanted: was not working with 
enchanted:
- SHARPNESS 5
added a toLowerCase to solve that issue. Did not add to custom namespaces tho.

Enchanted minecraft namespace bug

---

src/me/rockyhawk/commandpanels/inventory/InventorySaver.java

on item pickup, the maxstacks of items is not determined, which may cause some problems.
When a player switches from one menu of top+middle+bottom to another of top+middle+bottom, the item pickup event will be triggered. Then the listener only determines whether there are similar items in the player's backpack, which will result in the appearance of an iron sword with an amount of 2.
```
panels: 
Main_2_Top:
perm: default
rows: 5
title: Example
custom-item:
airs:
material: AIR
commands-on-open:
- open= Empty_Middle {Middle}
- open= Empty_Bottom {Bottom}
item:
'0':
material: PAPER
customdata: 31001
name: "#e78b8b上一页"
commands:
- "open= Main_1_Top"
- "sound= UI_BUTTON_CLICK"
Main_1_Top:
perm: default
rows: 5
title: Example
commands-on-open:
- open= Empty_Middle {Middle}
- open= Empty_Bottom …
```

fix itemstack amount error when pickup item with middle panel.

---

.idea/jarRepositories.xml
pom.xml
resource/config.yml
resource/plugin.yml
src/me/rockyhawk/commandpanels/CommandPanels.java
src/me/rockyhawk/commandpanels/Context.java
src/me/rockyhawk/commandpanels/configuration/ConfigHandler.java
src/me/rockyhawk/commandpanels/interaction/commands/CommandRunner.java
src/me/rockyhawk/commandpanels/interaction/commands/tags/BungeeTag.java
src/me/rockyhawk/commandpanels/interaction/commands/tags/SkriptTag.java
src/me/rockyhawk/commandpanels/manager/autosave/AutoSaveManager.java
src/me/rockyhawk/commandpanels/manager/open/OpenPanel.java
src/me/rockyhawk/commandpanels/manager/open/OpenRequirements.java

**Skript support**
Direct skript support so you dont have to hope sudo= works.
```
item:
'0':
material: COMMAND_BLOCK
name: '&6Execute Skript Command'
lore:
- '&7Click to run a Skript command'
- '&eExample: skript= heal %cp-player-name%'
commands:
- 'skript= heal %cp-player-name%'
'1':
material: REDSTONE
name: '&cExecute Skript Function'
lore:
- '&7Click to execute a Skript function'
- '&eExample: skript= myfunction arg1 arg2'
commands:
- 'skript= myfunction %cp-player-name% welcome'
'2':
material: PAPER
name: '&aRun Custom Skript'
lore:
- '&7Click to run custom Skript commands'
- '&eYou can run any Skript command registered'
- '&ein your .sk files'
commands:
- 'skript= customcommand %cp-player-name%'
- 'msg= &aSkript command executed!'
```
**Open requirements**
Open requirements will …

Skript support, Open requirements, Bungeetag bug

---

src/me/rockyhawk/commandpanels/interaction/commands/tags/SoundTag.java

If the provided sound name isn't found in the Sound enum, it now tries to play it as a string instead. This allows support for custom sounds defined via resource packs.

Custom Sound support 
